version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: lifenavigator-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lifenavigator
      POSTGRES_PASSWORD: lifenavigator_password
      POSTGRES_DB: lifenavigator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000' -c 'shared_buffers=256MB'

volumes:
  postgres_data: