#!/bin/bash

echo "🚀 Running all LifeNavigator migrations in order..."
echo ""
echo "Please run these SQL files in your Supabase SQL Editor in this order:"
echo ""
echo "1. ✅ 001_initial_schema.sql - Basic tables (users, financial_accounts, etc.)"
echo "2. ✅ 002_usage_tracking_and_tiers.sql - Subscription tiers and feature usage"
echo ""
echo "For the complete database with all features, run:"
echo "3. 📋 scripts/build-complete-database.sql - All additional tables with conflict handling"
echo ""
echo "Alternative: Run individual migrations (may have conflicts):"
echo "3. ⚠️  002_complete_financial_domain.sql - Advanced financial features"
echo "4. ⚠️  003_healthcare_domain.sql - Healthcare tables"
echo "5. ⚠️  004_integrations_sync.sql - Integration sync tables"
echo "6. ⚠️  005_crypto_custody_security.sql - Crypto and security features"
echo "7. ⚠️  006_user_profiles_preferences.sql - User profiles (conflicts with 002)"
echo "8. ⚠️  007_infrastructure_monitoring.sql - Monitoring and analytics"
echo ""
echo "After migrations are complete, run:"
echo "npx tsx scripts/create-demo-account.ts"