#!/bin/bash

echo "📋 Setting up Vercel environment variables for demo mode..."
echo ""
echo "Run these commands to set up your Vercel deployment for demo mode:"
echo ""
echo "# Set demo mode environment variables"
echo "vercel env add NEXT_PUBLIC_DEMO_MODE production"
echo "# Enter: true"
echo ""
echo "vercel env add NEXT_PUBLIC_SKIP_AUTH production" 
echo "# Enter: true"
echo ""
echo "# Add your Supabase credentials if not already set"
echo "vercel env add NEXT_PUBLIC_SUPABASE_URL production"
echo "vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production"
echo "vercel env add SUPABASE_SERVICE_ROLE_KEY production"
echo ""
echo "# Deploy with demo mode"
echo "vercel --prod"
echo ""
echo "🔐 To password protect your Vercel deployment:"
echo "1. Go to your Vercel project settings"
echo "2. Navigate to 'Advanced' → 'Password Protection'"
echo "3. Enable password protection"
echo "4. Set your desired password"
echo ""
echo "This will require visitors to enter a password before accessing the demo."